import Head from "next/head";
import Image from "next/image";
import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Container,
  createTheme,
  Grid,
  MantineProvider,
  Text,
  ThemeIcon,
  Title,
} from "@mantine/core";
import { SiGithub, SiLinkedin, SiStackoverflow } from "react-icons/si";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const theme = createTheme({
    colors: {
      // or replace default theme color
      dark: [
        "#ffffff",
        "#78e110",
        "#8600b3",
        "#0021c8",
        "#d4df08",
        "#14f814",
        "#d77e02",
        "#000000",
        "#79ea00",
        "#d80073",
      ],
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MantineProvider defaultColorScheme="dark" theme={theme}>
        <Container size="xl">
          <Grid>
            <Grid.Col
              span={{ xs: 6, sm: 6, md: 6, lg: 3, xl: 3 }}
              h="100vh"
              component="header"
            >
              <Title fw={500} mt="2rem" order={1}>
                Vidarshan
              </Title>
              <Title size={20} fw={400} order={2}>
                Software Engineer — Web, Mobile, AI & Cloud
              </Title>
              <Box mt="3rem" component="nav">
                <Box component="ul">
                  <Box component="li">
                    <Text size="xl" component="a" href="#">
                      About
                    </Text>
                  </Box>
                  <Box component="li">
                    <Text component="a" href="#">
                      Projects
                    </Text>
                  </Box>
                  <Box component="li">
                    <Text component="a" href="#">
                      Contact
                    </Text>
                  </Box>
                </Box>
              </Box>
              <Box mt="3rem">
                <SiGithub size={20} style={{ marginRight: "6px" }} />

                <SiStackoverflow size={20} style={{ marginRight: "6px" }} />

                <SiLinkedin size={20} style={{ marginRight: "6px" }} />
              </Box>
            </Grid.Col>

            <Grid.Col
              span={{ xs: 6, sm: 6, md: 6, lg: 9, xl: 9 }}
              component="main"
            >
              content goes here
            </Grid.Col>
          </Grid>
        </Container>

        <footer className={styles.footer}></footer>
      </MantineProvider>
    </>
  );
}
