import Head from "next/head";
import Image from "next/image";
import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ActionIcon,
  Badge,
  Box,
  Button,
  Card,
  Center,
  Container,
  createTheme,
  Divider,
  Flex,
  Grid,
  Group,
  MantineProvider,
  SegmentedControl,
  Text,
  ThemeIcon,
  Title,
  Transition,
} from "@mantine/core";
import {
  SiGithub,
  SiLinkedin,
  SiNextdotjs,
  SiOpenai,
  SiStackoverflow,
} from "react-icons/si";
import { useEffect, useState } from "react";
import Experience from "./components/Experience";
import { PiSparkle } from "react-icons/pi";
import { FiMoreHorizontal } from "react-icons/fi";
import Education from "./components/Education";
import {
  ICertificationProps,
  IEducationProps,
  IExperienceProps,
  IProject,
} from "./interfaces";

import experience from "@/pages/data/work";
import education from "@/pages/data/education";
import certifications from "@/pages/data/certifications";
import projects from "@/pages/data/projects";

import Certification from "./components/Certification";
import work from "@/pages/data/work";
import Project from "./components/Project";
import { VscAdd } from "react-icons/vsc";
import {
  RiAddLargeLine,
  RiGithubFill,
  RiLinkedinBoxFill,
  RiStackOverflowFill,
  RiSubtractFill,
  RiTwitterXFill,
} from "react-icons/ri";
import Socials from "./components/Socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const theme = createTheme({
    colors: {
      // or replace default theme color
      dark: [
        "#ffffff",
        "#b0b0b0",
        "#8600b3",
        "#0021c8",
        "#323232",
        "#ffffff",
        "#000000",
        "#000000",
        "#242424d5",
        "#d80073",
      ],
    },
    defaultRadius: "lg",
    fontSizes: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
    },
    lineHeights: {
      md: "1.8rem",
    },
  });
  const sections = ["about", "experience", "projects"];

  const [activeSection, setActiveSection] = useState("about");
  const [educationOpened, setEducationOpened] = useState(false);
  const [certificationsOpened, setCertificationsOpened] = useState(false);

  useEffect(() => {
    const scrollContainer = document.querySelector("main"); // the Grid.Col main
    if (!scrollContainer) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      {
        root: scrollContainer, // ← observe relative to main, not viewport
        threshold: 0.5,
      }
    );

    sections.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MantineProvider defaultColorScheme="dark" theme={theme}>
        <Container h="100vh" size={1200}>
          <Grid>
            <Grid.Col
              span={{ xs: 6, sm: 6, md: 6, lg: 4, xl: 4 }}
              h="100vh"
              component="header"
            >
              <Flex h="80%" direction="column" justify="space-around">
                <Box>
                  <Text
                    className="apple-text"
                    size="2.4rem"
                    fw={400}
                    // order={1}
                  >
                    Vidarshan
                  </Text>
                  <Title c="gray" size="1.2rem" fw={400} order={2}>
                    Software Engineer — Web, Mobile, AI & Cloud
                  </Title>
                  <Socials />
                </Box>

                <Flex direction="column" component="nav">
                  {sections.map((id) => (
                    <Text
                      key={id}
                      component="a"
                      href={`#${id}`}
                      className="ai-text"
                      mb={20}
                      style={{
                        transition: "all 0.3s ease", // <--- smooth animation
                      }}
                      size={activeSection === `${id}` ? "2rem" : "1rem"}
                      // fw={activeSection === `${id}` ? 700 : 400}
                    >
                      {id.charAt(0).toUpperCase() + id.slice(1)}
                    </Text>
                  ))}
                </Flex>
              </Flex>
            </Grid.Col>

            <Grid.Col
              span={{ xs: 6, sm: 6, md: 6, lg: 8, xl: 8 }}
              style={{ overflowY: "scroll", scrollBehavior: "smooth" }}
              h="100vh"
              component="main"
            >
              <Box my="xl" id="about" component="section">
                <Text>
                  I design and build digital products that make work simpler,
                  smarter, and more enjoyable. With nearly four years of
                  software engineering experience, I create solutions that don’t
                  just function; they elevate user experiences and drive real
                  results.
                </Text>
                <Text mt="lg">
                  Curious by nature and driven by impact, I explore emerging
                  tech in AI and cloud infrastructure to push products beyond
                  the expected --whether through smarter automation,
                  personalization, or rock-solid scalability. I thrive on
                  turning complex challenges into intuitive, future-ready
                  software that aligns perfectly with user and business goals.
                </Text>

                <Flex my="sm" align="center" justify="space-between">
                  <Text fw={500}>Certifications</Text>
                  <ActionIcon
                    onClick={() =>
                      setCertificationsOpened(!certificationsOpened)
                    }
                    variant="light"
                    color="cyan"
                  >
                    {certificationsOpened ? (
                      <RiSubtractFill />
                    ) : (
                      <RiAddLargeLine />
                    )}
                  </ActionIcon>
                </Flex>
                {certificationsOpened && (
                  <Grid>
                    {certifications.map((cert: ICertificationProps) => {
                      return <Certification key={cert.title} {...cert} />;
                    })}
                  </Grid>
                )}
                <Flex my="sm" align="center" justify="space-between">
                  <Text mt="sm" fw={500}>
                    Education
                  </Text>
                  <ActionIcon
                    onClick={() => setEducationOpened(!educationOpened)}
                    variant="light"
                    color="cyan"
                  >
                    {educationOpened ? <RiSubtractFill /> : <RiAddLargeLine />}
                  </ActionIcon>
                </Flex>
                {educationOpened && (
                  <Grid>
                    {education.map((edu: IEducationProps) => {
                      return <Education key={edu.title} {...edu} />;
                    })}
                  </Grid>
                )}
              </Box>
              <Box id="experience" component="section">
                {work.map(({ company, jobs, link }) => (
                  <Experience
                    key={company}
                    jobs={jobs}
                    company={company}
                    link={link}
                  />
                ))}
                {/* <Title order={3}>Experience</Title> */}
              </Box>
              <Box id="projects" component="section">
                <SegmentedControl
                  radius="xl"
                  size="sm"
                  variant="filled"
                  color="dark"
                  data={[
                    {
                      value: "preview",
                      label: (
                        <Center style={{ gap: 10 }}>
                          {/* <IconEye size={16} /> */}
                          <span>Projects</span>
                        </Center>
                      ),
                    },
                    {
                      value: "code",
                      label: (
                        <Center style={{ gap: 10 }}>
                          {/* <IconCode size={16} /> */}
                          <span>Archive</span>
                        </Center>
                      ),
                    },
                  ]}
                />
                <Text>Projects</Text>
                {projects.map((project) => {
                  return <Project key={project.name} {...project} />;
                })}
              </Box>
            </Grid.Col>
          </Grid>
        </Container>

        <footer className={styles.footer}></footer>
      </MantineProvider>
    </>
  );
}
